<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Koperasi_pusat_model extends CI_Model
{

    public $table = 'koperasi_pusat';
    public $id = 'nisat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function get_propinsi(){
        $provinsi = $this->db->get('provinsi');
        return $provinsi->result();
    }
    function get_niki(){
        $niki = $this->db->get('koperasi_induk');
        return $niki->result();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nisat', $q);
	$this->db->or_like('niki', $q);
	$this->db->or_like('nama_koperasi_pusat', $q);
	$this->db->or_like('nama_depan', $q);
	$this->db->or_like('nama_belakang', $q);
	$this->db->or_like('kode_propinsi', $q);
	$this->db->or_like('no_hp_wa', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nisat', $q);
	$this->db->or_like('niki', $q);
	$this->db->or_like('nama_koperasi_pusat', $q);
	$this->db->or_like('nama_depan', $q);
	$this->db->or_like('nama_belakang', $q);
	$this->db->or_like('kode_propinsi', $q);
	$this->db->or_like('no_hp_wa', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_limit_data2($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nisat', $q);
	$this->db->or_like('niki', $q);
	$this->db->or_like('nama_koperasi_pusat', $q);
	$this->db->or_like('nama_depan', $q);
	$this->db->or_like('nama_belakang', $q);
	$this->db->or_like('kode_propinsi', $q);
	$this->db->or_like('no_hp_wa', $q);
	$this->db->limit($limit, $start);
        //return $this->db->get('$this->table')->result();
        //return $this->db->get('vw_pusat')->result();
return $this->db->query("SELECT
`arnevaco_register`.`koperasi_pusat`.`niki` AS `niki`,
`arnevaco_register`.`koperasi_pusat`.`nisat` AS `nisat`,
`arnevaco_register`.`koperasi_pusat`.`nama_koperasi_pusat` AS `nama_koperasi_pusat`,
`arnevaco_register`.`koperasi_pusat`.`nama_depan` AS `nama_depan`,
`arnevaco_register`.`koperasi_pusat`.`nama_belakang` AS `nama_belakang`,
`arnevaco_register`.`koperasi_pusat`.`kode_propinsi` AS `kode_propinsi`,
`arnevaco_register`.`koperasi_pusat`.`no_hp_wa` AS `no_hp_wa`,
`arnevaco_register`.`koperasi_induk`.`niki` AS `nikis`,
`arnevaco_register`.`koperasi_induk`.`nama_koperasi_induk` AS `nama_koperasi_induk`,
`arnevaco_register`.`provinsi`.`nama_prop` AS `nama_prop`
FROM
(
    (
        `arnevaco_register`.`koperasi_pusat`
    JOIN `arnevaco_register`.`koperasi_induk`
    )
JOIN `arnevaco_register`.`provinsi`
)
WHERE
`arnevaco_register`.`koperasi_induk`.`niki` = `arnevaco_register`.`koperasi_pusat`.`niki` AND `arnevaco_register`.`provinsi`.`id_propinsi` = `arnevaco_register`.`koperasi_pusat`.`kode_propinsi`")->result();
        //return $this->db->query("SELECT koperasi_pusat.*,koperasi_induk.niki AS 'nikis',koperasi_induk.nama_koperasi_induk,provinsi.nama_prop FROM koperasi_pusat,koperasi_induk,provinsi WHERE koperasi_induk.niki=koperasi_pusat.niki AND provinsi.id_propinsi=koperasi_pusat.kode_propinsi")->result();
    }
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Koperasi_pusat_model.php */
/* Location: ./application/models/Koperasi_pusat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-17 21:01:16 */
/* http://harviacode.com */